# WARNING! This file is automatically generated by "rake gen".
# WARNING! Any modification to it would be lost after another "rake gen" operation!

# Automatically generated at Fri May 14 09:55:13 +0800 2010

CC=gcc
CFLAGS=-ggdb -pthread -Wall -Isrc -Ixdk -Itest -I3rdparty  -D_FILE_OFFSET_BITS=64
LDFLAGS=-lpthread -lm

default: bin obj src 

bin:
	mkdir -p bin

obj:
	mkdir -p obj/3rdparty/vnc_auth
	mkdir -p obj/src
	mkdir -p obj/test
	mkdir -p obj/xdk/3rdparty/bigint
	mkdir -p obj/xdk/3rdparty/crypto/md5
	mkdir -p obj/xdk/3rdparty/crypto/sha1


api: 3rdparty/vnc_auth/d3des.h 3rdparty/vnc_auth/d3des.c src/vnc_proxy_ctl.c src/vnc_proxy.c xdk/xhash.h xdk/xmemory.h xdk/xdef.c xdk/xkeepalive.h xdk/xhash.c xdk/xutils.c xdk/xcrypto.h xdk/xoption.h xdk/xlog.h xdk/xsys.c xdk/xnet.c xdk/xstr.c xdk/xconf.h xdk/xoption.c xdk/xvec.h xdk/xconf.c xdk/xcrypto.c xdk/xsys.h xdk/xutils.h xdk/xlog.c xdk/xmemory.c xdk/xnet.h xdk/xvec.c xdk/xkeepalive.c xdk/xbigint.c xdk/xbigint.h xdk/3rdparty/crypto/md5/md5.h xdk/3rdparty/crypto/md5/md5.c xdk/3rdparty/crypto/sha1/sha1.h xdk/3rdparty/crypto/sha1/sha1.c xdk/3rdparty/bigint/bigint.h xdk/3rdparty/bigint/bigint.c xdk/xstr.h xdk/xdef.h 
	doxygen


clean:
	rm -rf bin
	rm -rf obj
	rm -rf api
	rm -f *.log
	find . -iname *~ -delete

3rdparty: bin obj obj/3rdparty/vnc_auth/d3des.o

obj/3rdparty/vnc_auth/d3des.o: 3rdparty/vnc_auth/d3des.c 3rdparty/vnc_auth/d3des.h
	$(CC) $(CFLAGS) -c 3rdparty/vnc_auth/d3des.c -o obj/3rdparty/vnc_auth/d3des.o


bin/vnc_proxy: obj/3rdparty/vnc_auth/d3des.o obj/src/vnc_proxy.o obj/xdk/3rdparty/crypto/md5/md5.o obj/xdk/3rdparty/crypto/sha1/sha1.o obj/xdk/xconf.o obj/xdk/xcrypto.o obj/xdk/xdef.o obj/xdk/xhash.o obj/xdk/xlog.o obj/xdk/xmemory.o obj/xdk/xnet.o obj/xdk/xoption.o obj/xdk/xstr.o obj/xdk/xsys.o obj/xdk/xutils.o obj/xdk/xvec.o
	$(CC) $(CFLAGS) $(LDFLAGS) obj/src/vnc_proxy.o obj/3rdparty/vnc_auth/d3des.o obj/xdk/3rdparty/crypto/md5/md5.o obj/xdk/3rdparty/crypto/sha1/sha1.o obj/xdk/xconf.o obj/xdk/xcrypto.o obj/xdk/xdef.o obj/xdk/xhash.o obj/xdk/xlog.o obj/xdk/xmemory.o obj/xdk/xnet.o obj/xdk/xoption.o obj/xdk/xstr.o obj/xdk/xsys.o obj/xdk/xutils.o obj/xdk/xvec.o -o bin/vnc_proxy

bin/vnc_proxy_ctl: obj/src/vnc_proxy_ctl.o obj/xdk/3rdparty/crypto/md5/md5.o obj/xdk/3rdparty/crypto/sha1/sha1.o obj/xdk/xcrypto.o obj/xdk/xdef.o obj/xdk/xmemory.o obj/xdk/xstr.o obj/xdk/xsys.o obj/xdk/xutils.o
	$(CC) $(CFLAGS) $(LDFLAGS) obj/src/vnc_proxy_ctl.o obj/xdk/3rdparty/crypto/md5/md5.o obj/xdk/3rdparty/crypto/sha1/sha1.o obj/xdk/xcrypto.o obj/xdk/xdef.o obj/xdk/xmemory.o obj/xdk/xstr.o obj/xdk/xsys.o obj/xdk/xutils.o -o bin/vnc_proxy_ctl

obj/src/vnc_proxy.o: 3rdparty/vnc_auth/d3des.h src/vnc_proxy.c xdk/xcrypto.h xdk/xlog.h xdk/xmemory.h xdk/xnet.h xdk/xstr.h xdk/xutils.h xdk/xvec.h
	$(CC) $(CFLAGS) -c src/vnc_proxy.c -o obj/src/vnc_proxy.o

obj/src/vnc_proxy_ctl.o: src/vnc_proxy_ctl.c xdk/xdef.h xdk/xmemory.h xdk/xstr.h xdk/xutils.h
	$(CC) $(CFLAGS) -c src/vnc_proxy_ctl.c -o obj/src/vnc_proxy_ctl.o

src: bin obj bin/vnc_proxy bin/vnc_proxy_ctl obj/src/vnc_proxy.o obj/src/vnc_proxy_ctl.o


runtest: test
	@clear
	@echo Running test module \'test\'
	@echo ==========================

test: bin obj 


obj/xdk/3rdparty/bigint/bigint.o: xdk/3rdparty/bigint/bigint.c xdk/3rdparty/bigint/bigint.h xdk/xbigint.h
	$(CC) $(CFLAGS) -c xdk/3rdparty/bigint/bigint.c -o obj/xdk/3rdparty/bigint/bigint.o

obj/xdk/3rdparty/crypto/md5/md5.o: xdk/3rdparty/crypto/md5/md5.c xdk/3rdparty/crypto/md5/md5.h
	$(CC) $(CFLAGS) -c xdk/3rdparty/crypto/md5/md5.c -o obj/xdk/3rdparty/crypto/md5/md5.o

obj/xdk/3rdparty/crypto/sha1/sha1.o: xdk/3rdparty/crypto/sha1/sha1.c xdk/3rdparty/crypto/sha1/sha1.h
	$(CC) $(CFLAGS) -c xdk/3rdparty/crypto/sha1/sha1.c -o obj/xdk/3rdparty/crypto/sha1/sha1.o

obj/xdk/xbigint.o: xdk/3rdparty/bigint/bigint.h xdk/xbigint.c xdk/xbigint.h xdk/xdef.h xdk/xmemory.h xdk/xstr.h
	$(CC) $(CFLAGS) -c xdk/xbigint.c -o obj/xdk/xbigint.o

obj/xdk/xconf.o: xdk/xconf.c xdk/xconf.h xdk/xdef.h xdk/xhash.h xdk/xmemory.h xdk/xstr.h xdk/xutils.h
	$(CC) $(CFLAGS) -c xdk/xconf.c -o obj/xdk/xconf.o

obj/xdk/xcrypto.o: xdk/3rdparty/crypto/md5/md5.h xdk/3rdparty/crypto/sha1/sha1.h xdk/xcrypto.c xdk/xcrypto.h xdk/xdef.h xdk/xmemory.h
	$(CC) $(CFLAGS) -c xdk/xcrypto.c -o obj/xdk/xcrypto.o

obj/xdk/xdef.o: xdk/xdef.c xdk/xdef.h
	$(CC) $(CFLAGS) -c xdk/xdef.c -o obj/xdk/xdef.o

obj/xdk/xhash.o: xdk/xdef.h xdk/xhash.c xdk/xhash.h xdk/xmemory.h
	$(CC) $(CFLAGS) -c xdk/xhash.c -o obj/xdk/xhash.o

obj/xdk/xkeepalive.o: xdk/xdef.h xdk/xkeepalive.c xdk/xkeepalive.h xdk/xlog.h xdk/xutils.h
	$(CC) $(CFLAGS) -c xdk/xkeepalive.c -o obj/xdk/xkeepalive.o

obj/xdk/xlog.o: xdk/xdef.h xdk/xlog.c xdk/xlog.h xdk/xoption.h xdk/xsys.h xdk/xutils.h
	$(CC) $(CFLAGS) -c xdk/xlog.c -o obj/xdk/xlog.o

obj/xdk/xmemory.o: xdk/xdef.h xdk/xmemory.c xdk/xmemory.h
	$(CC) $(CFLAGS) -c xdk/xmemory.c -o obj/xdk/xmemory.o

obj/xdk/xnet.o: xdk/xdef.h xdk/xlog.h xdk/xmemory.h xdk/xnet.c xdk/xnet.h xdk/xstr.h xdk/xutils.h
	$(CC) $(CFLAGS) -c xdk/xnet.c -o obj/xdk/xnet.o

obj/xdk/xoption.o: xdk/xconf.h xdk/xdef.h xdk/xhash.h xdk/xlog.h xdk/xmemory.h xdk/xoption.c xdk/xoption.h xdk/xstr.h xdk/xutils.h xdk/xvec.h
	$(CC) $(CFLAGS) -c xdk/xoption.c -o obj/xdk/xoption.o

obj/xdk/xstr.o: xdk/xdef.h xdk/xmemory.h xdk/xstr.c xdk/xstr.h xdk/xutils.h
	$(CC) $(CFLAGS) -c xdk/xstr.c -o obj/xdk/xstr.o

obj/xdk/xsys.o: xdk/xsys.c xdk/xsys.h
	$(CC) $(CFLAGS) -c xdk/xsys.c -o obj/xdk/xsys.o

obj/xdk/xutils.o: xdk/xcrypto.h xdk/xdef.h xdk/xmemory.h xdk/xstr.h xdk/xsys.h xdk/xutils.c xdk/xutils.h
	$(CC) $(CFLAGS) -c xdk/xutils.c -o obj/xdk/xutils.o

obj/xdk/xvec.o: xdk/xmemory.h xdk/xvec.c xdk/xvec.h
	$(CC) $(CFLAGS) -c xdk/xvec.c -o obj/xdk/xvec.o

xdk: bin obj obj/xdk/3rdparty/bigint/bigint.o obj/xdk/3rdparty/crypto/md5/md5.o obj/xdk/3rdparty/crypto/sha1/sha1.o obj/xdk/xbigint.o obj/xdk/xconf.o obj/xdk/xcrypto.o obj/xdk/xdef.o obj/xdk/xhash.o obj/xdk/xkeepalive.o obj/xdk/xlog.o obj/xdk/xmemory.o obj/xdk/xnet.o obj/xdk/xoption.o obj/xdk/xstr.o obj/xdk/xsys.o obj/xdk/xutils.o obj/xdk/xvec.o


all: bin obj bin/vnc_proxy bin/vnc_proxy_ctl obj/3rdparty/vnc_auth/d3des.o obj/src/vnc_proxy.o obj/src/vnc_proxy_ctl.o obj/xdk/3rdparty/bigint/bigint.o obj/xdk/3rdparty/crypto/md5/md5.o obj/xdk/3rdparty/crypto/sha1/sha1.o obj/xdk/xbigint.o obj/xdk/xconf.o obj/xdk/xcrypto.o obj/xdk/xdef.o obj/xdk/xhash.o obj/xdk/xkeepalive.o obj/xdk/xlog.o obj/xdk/xmemory.o obj/xdk/xnet.o obj/xdk/xoption.o obj/xdk/xstr.o obj/xdk/xsys.o obj/xdk/xutils.o obj/xdk/xvec.o 



